version: "3.9"

services:
  php:
    container_name: php
    image: php
    restart: always
    build:
      context: ./phpapp
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:80"
    command: php -S 0.0.0.0:80 -t /var/www/html

  nginx:
    image: nginx
    ports:
      - "80:80"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    command: php /var/www/html/client.php
    depends_on:
      - php
